#ifndef ATOM
#error Need to define ATOM before including this file!
#endif

ATOM(UTF8_STRING)

ATOM(CLIPBOARD)
ATOM(TARGETS)
ATOM(INCR)

ATOM(WM_PROTOCOLS)
ATOM(WM_DELETE_WINDOW)

ATOM(_MOTIF_WM_HINTS)

ATOM(WM_NAME)
ATOM(_NET_WM_NAME)
ATOM(WM_ICON_NAME)
ATOM(_NET_WM_ICON_NAME)

ATOM(_NET_WM_WINDOW_TYPE)
ATOM(_NET_WM_WINDOW_TYPE_DROPDOWN_MENU)
ATOM(_NET_WM_WINDOW_TYPE_POPUP_MENU)
ATOM(_NET_WM_WINDOW_TYPE_NORMAL)

ATOM(_NET_WM_STATE)
ATOM(_NET_WM_STATE_MODAL)
